name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: Set output
        id: set-output
        run: echo "echo_msg=true" >> $GITHUB_OUTPUT
    outputs:
      echo_msg: ${{ steps.set-output.outputs.echo_msg }}

  other-job:
    runs-on: ubuntu-latest
    needs: my-job
    continue-on-error: true
    steps:
      - name: Echo something
        run: exit 1

  is-true-job:
    runs-on: ubuntu-latest
    needs: [my-job, other-job]
    if: ${{ needs.my-job.outputs.echo_msg == 'true' }}
    steps:
      - name: It works
        run: echo "It works"