name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: Set output
        id: set-output
        run: echo "echo_msg=false" >> $GITHUB_OUTPUT
    outputs:
      echo_msg: ${{ steps.set-output.outputs.echo_msg }}

  is-true-job:
    runs-on: ubuntu-latest
    needs: my-job
    if: ${{ needs.my-job.outputs.echo_msg == 'true' }}
    steps:
      - name: Echo something
        run: echo "I need to echo something!"

  is-false-job:
    runs-on: ubuntu-latest
    needs: my-job
    if: ${{ needs.my-job.outputs.echo_msg != 'true' }}
    steps:
      - name: Shut up
        run: echo "I shut up"